es:
    build: es-docker

gitlist:
    build: gitlist-docker
    ports:
        - "8090:80"

kibana:
    build: kibana-docker
    links:
        - es:elasticsearch
    ports:
        - "8080:80"

logstash:
    build: logstash-docker
    command: --elasticsearch=elasticsearch
    links:
        - es:elasticsearch
    volumes_from:
        - gitlist
